name: Generate Profile Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: maurodesouza/profile-readme-stats@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
